language: csharp
solution: ./src/StudyTdd.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ./src/StudyTdd.sln
after_script:
  - nunit-console ./src/StudyTddTest/bin/Release/StudyTddTest.dll